/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Gift.types";
import * as _1 from "./Gift.client";
import * as _2 from "./Passport.types";
import * as _3 from "./Passport.client";
export namespace contracts {
  export const Gift = { ..._0,
    ..._1
  };
  export const Passport = { ..._2,
    ..._3
  };
}